version: '3.2'

services:
  elasticsearch:
    image: stag-docker-repo.clix.io:5000/dockerelk_elasticsearch:latest
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9201:9201"
      - "9301:9301"
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    image: stag-docker-repo.clix.io:5000/dockerelk_logstash:latest
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      elk:
        aliases:
          - logstash
    depends_on:
      - elasticsearch

  kibana:
    image: stag-docker-repo.clix.io:5000/dockerelk_kibana:latest
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 60s
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5602:5602"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logspout:
    image: stag-docker-repo.clix.io:5000/logspout-logstash
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    environment:
      ROUTE_URIS: "logstash+tcp://logstash:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    depends_on:
      - logstash
    networks:
      - elk
    
networks:
  elk:
    driver: overlay
